apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: omarelsady/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom: #env variable to store the NATS client ID
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222' #env variable to store the NATS server URL
            - name: NATS_CLUSTER_ID
              value: 'ticketing' #env variable to store the NATS cluster ID
            - name: REDIS_HOST
              value: 'expiration-redis-srv' #env variable to store the Redis server host
